[config]
custom_model_max_tokens = 128000

[pr_reviewer]
persistent_comment = true
final_update_message = false
extra_instructions = """
Анализируй треды и комментарии существующего PR. Не оставляй комментариев по проблемам которые
были описаны другими ревьюверами (даже если это боты). Если ты не согласен с описанием или имеешь
альтернативное решение - напиши об этом в треде.
Пиши комментарии на русском языке.
"""

[pr_code_suggestions]
persistent_comment = true
num_code_suggestions = 6
