spring.application.name=notifications

# Telegram API
bot.enabled=true
bot.token=${TG_BOT_TOKEN}

# Database
spring.datasource.url=jdbc:postgresql://${DB_ADDRESS}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

mybatis.mapper-locations=classpath*:/mapper/*.xml
mybatis.configuration.arg-name-based-constructor-auto-mapping=true
mybatis.configuration.map-underscore-to-camel-case=true


# Web
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Spring AI
spring.ai.mcp.server.name="DADS Notification"
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

# File Storage
file.upload.directory=/data/files
file.ttl=1d
file.cleaner.cron=0 0 0 * * *

# API
security.x-api-key=${X_API_KEY}

# For local run
#mcp.roots=D:\\MCP\\telegram-downloads
#spring.ai.mcp.server.stdio=true
#logging.level.root=OFF
#spring.main.banner-mode=off