spring.application.name=notifications

# Telegram API
bot.enabled=true
bot.token=${TG_BOT_TOKEN}

spring.datasource.url=jdbc:postgresql://${DB_ADDRESS}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#spring.servlet.multipart.max-file-size=20MB
#spring.servlet.multipart.max-request-size=20MB

spring.ai.mcp.server.name="DADS Notification"
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.server.enabled=true

mybatis.mapper-locations=classpath*:/mapper/*.xml
mybatis.configuration.arg-name-based-constructor-auto-mapping=true
mybatis.configuration.map-underscore-to-camel-case=true

file.upload.directory=/data/files
file.ttl=1d
file.cleaner.cron=0 0 0 * * *

security.x-api-key=${FILE_API_KEY}


# For local run
#mcp.roots=D:\\MCP\\telegram-downloads
#spring.ai.mcp.server.stdio=true
#logging.level.root=OFF
#spring.main.banner-mode=off